#pragma once
#include "Resolver.h"

// Auto-generated by Il2CppResolver

template<int32_t Len>
struct StringLiteral
{
    char Chars[Len];

    consteval StringLiteral(const char(&String)[Len])
    {
        std::copy_n(String, Len, Chars);
    }

    operator std::string() const
    {
        return static_cast<const char*>(Chars);
    }
};

template<StringLiteral Namespace, StringLiteral Name>
inline Il2CppClass* GetCachedClass() {
    static Il2CppClass* Cached = nullptr;
    if (!Cached)
    {
        // Fast Lookup (Assembly-CSharp)
        Il2CppImage* img = Image::GetByName("Assembly-CSharp");
        if(img) Cached = UnityClass::GetFromName(img, Namespace.Chars, Name.Chars);
        
        // Fallback: Search ALL Assemblies
        if (!Cached)
            Cached = UnityClass::Find(Namespace.Chars, Name.Chars);
    }
    return Cached;
}


namespace StaticClasses
{
    // Paste the generated classes here
}