#pragma once
#include <string>
#include <algorithm>
#include <cstdint>
#include "Resolver.h"

// Auto-generated by Il2CppResolver
template<StringLiteral Namespace, StringLiteral Name>
inline Il2CppClass* GetCachedClass() {
    static Il2CppClass* Cached = nullptr;
    if (!Cached)
    {
        // Fast Lookup (Assembly-CSharp)
        Il2CppImage* img = Image::GetByName("Assembly-CSharp");
        if(img) Cached = UnityClass::GetFromName(img, Namespace.Chars, Name.Chars);
        
        // Fallback: Search ALL Assemblies
        if (!Cached)
            Cached = UnityClass::Find(Namespace.Chars, Name.Chars);
    }
    return Cached;
}

namespace StaticClasses
{

}
