//
//  DumpUnityClass.h
//  Asura
//
//  Created by Euclid Jan Guillermo on 2/5/26.
//

#pragma once
#include "Helpers.h"

static void DumpUnityClasses()
{
    std::vector<std::string> Data;

    // Headers
    Data.push_back("#pragma once\n");
    Data.push_back("#include <string>\n");
    Data.push_back("#include <algorithm>\n");
    Data.push_back("#include <cstdint>\n"); // Needed for int32
    Data.push_back("#include \"Resolver.h\"\n\n");
    Data.push_back("// Auto-generated by Il2CppResolver\n\n");
    
    Data.push_back(
        "template<StringLiteral Namespace, StringLiteral Name>\n"
        "inline Il2CppClass* GetCachedClass() {\n"
        "    static Il2CppClass* Cached = nullptr;\n"
        "    if (!Cached)\n"
        "    {\n"
        "        // Fast Lookup (Assembly-CSharp)\n"
        "        Il2CppImage* img = Image::GetByName(\"Assembly-CSharp\");\n"
        "        if(img) Cached = UnityClass::GetFromName(img, Namespace.Chars, Name.Chars);\n"
        "        \n"
        "        // Fallback: Search ALL Assemblies\n"
        "        if (!Cached)\n"
        "            Cached = UnityClass::Find(Namespace.Chars, Name.Chars);\n"
        "    }\n"
        "    return Cached;\n"
        "}\n\n"
    );

    Data.push_back("namespace StaticClasses\n{\n");

    // Iterate and Generate
    size_t AssemblyCount = 0;
    Il2CppAssembly** Assemblies = Domain::GetAssemblies(&AssemblyCount);

    if (Assemblies)
    {
        std::set<std::string> GeneratedFunctions;

        for (size_t i = 0; i < AssemblyCount; i++)
        {
            Il2CppImage* Image = Assemblies[i]->m_pImage;
            if (!Image) continue;

            size_t ClassCount = Image::GetClassCount(Image);

            for (size_t j = 0; j < ClassCount; j++)
            {
                Il2CppClass* Klass = Image::GetClass(Image, j);
                if (!Klass) continue;

                const char* namePtr = Klass->m_pName;
                const char* nsPtr = Klass->m_pNamespace;

                std::string Name = namePtr ? namePtr : "";
                std::string Namespace = nsPtr ? nsPtr : "";

                if (Name.empty() || Name.find("<") != std::string::npos || Name.find("$") != std::string::npos)
                    continue;

                std::string FuncName = Name;
                if (!Namespace.empty()) FuncName = Namespace + "_" + Name;
                
                FuncName = SanitizeClass(FuncName);

                if (GeneratedFunctions.count(FuncName)) continue;
                GeneratedFunctions.insert(FuncName);

                // Generate line
                std::string Output = "    inline Il2CppClass* " + FuncName + "() { return GetCachedClass<\"" + Namespace + "\", \"" + Name + "\">(); }\n";
                Data.push_back(Output);
            }
        }
    }

    Data.push_back("}\n");
    DumpToFile("StaticClasses.h", Data);
}
